name: Release

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
          - platform: darwin/universal
            os: macos-latest
          - platform: windows/amd64
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: snider/build@v3
        with:
          build-name: dispatch
          build-platform: ${{ matrix.platform }}
          go-version: '1.23'
          nsis: ${{ matrix.os == 'windows-latest' }}
          node-version: '20'
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
